-- PROVEEDORES

INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (10, 'XAXX010101000-U1', 'URBANO CASTILLO CENTRAL DE ABASTOS', NULL, NULL, true, '2025-10-21 12:57:52', '2025-10-21 12:57:52', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (11, 'AFA8807024B1', 'Abarrotes Fasti S.A. de C.V. .', NULL, NULL, true, '2025-10-21 12:58:37', '2025-10-21 12:58:37', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (9, 'NWM9709244W4', 'Sam''s Club México.', NULL, NULL, true, '2025-10-21 12:50:23', '2025-10-21 12:59:02', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (12, 'CCA8805089W1', 'Costco de México.', NULL, NULL, true, '2025-10-21 12:59:24', '2025-10-21 12:59:24', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (13, 'CCO670202HB7', 'Coca-Cola Femsa Veracruz', NULL, NULL, true, '2025-10-21 12:59:50', '2025-10-21 12:59:50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (14, 'DCO100916H51', 'Distribuidora Comercial Oriental .', NULL, NULL, true, '2025-10-21 13:00:12', '2025-10-21 13:00:12', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (15, 'BIM4601016X8', 'Grupo Bimbo', NULL, NULL, true, '2025-10-21 13:00:34', '2025-10-21 13:00:34', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (16, 'CHE8507029B1', 'Chedraui Veracruz filial', NULL, NULL, true, '2025-10-21 13:01:17', '2025-10-21 13:01:17', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (17, 'LJO9201012B1', 'Quesos La Joya Liz S.A. de C.V.', NULL, NULL, true, '2025-10-21 13:01:38', '2025-10-21 13:01:38', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (18, 'XAXX010101000-MP', 'MATERIAS PRIMAS LA AZTECA', NULL, NULL, true, '2025-10-21 13:02:04', '2025-10-21 13:02:04', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (19, 'XAXX010101000-CP', 'COAPEXPAN CARNES FRIAS', NULL, NULL, true, '2025-10-21 13:02:12', '2025-10-21 13:02:12', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (20, 'OFS000526912', 'EL BODEGON DE SEMILLAS, S.A. DE C.V.', NULL, NULL, true, '2025-10-21 13:03:03', '2025-10-21 13:03:03', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (21, 'XAXX010101000-FC', 'FERCAS', NULL, NULL, true, '2025-10-21 13:04:51', '2025-10-21 13:04:51', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (22, 'XAXX010101000-FR', 'FRUTA', NULL, NULL, true, '2025-10-21 13:05:03', '2025-10-21 13:05:03', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (23, 'XAXX010101000-PK', 'PANADERIA KAREN', NULL, NULL, true, '2025-10-21 13:05:19', '2025-10-21 13:05:19', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (24, 'XAXX010101000-GN', 'GENERICO', NULL, NULL, true, '2025-10-21 13:05:57', '2025-10-21 13:05:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (25, 'XAXX010101000-SL', 'SAN LUIS', NULL, NULL, true, '2025-10-21 13:06:13', '2025-10-21 13:06:13', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (26, 'XAXX010101000-PE', 'POLLERIA EL DORADO', NULL, NULL, true, '2025-10-21 13:07:44', '2025-10-21 13:07:44', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (27, 'XAXX010101000-QV', 'QUESOS Y ABARROTES VERONICA', NULL, NULL, true, '2025-10-21 13:08:00', '2025-10-21 13:08:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO cat_proveedores (id, rfc, nombre, telefono, email, activo, created_at, updated_at, razon_social, tipo_comprobante, uso_cfdi, metodo_pago, forma_pago, regimen_fiscal, contacto_nombre, contacto_email, contacto_telefono, direccion, ciudad, estado, pais, cp, notas) VALUES (28, 'XAXX010101000-VD', 'VERDURAS', NULL, NULL, true, '2025-10-21 13:08:10', '2025-10-21 13:08:10', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


--- ALMACENES

INSERT INTO cat_almacenes (id, clave, nombre, sucursal_id, activo, created_at, updated_at) VALUES (53, 'NB', 'Na Balam', 18, true, '2025-10-21 05:06:10', '2025-10-21 05:06:10');
INSERT INTO cat_almacenes (id, clave, nombre, sucursal_id, activo, created_at, updated_at) VALUES (54, 'TORRE', 'Torre UX', 20, true, '2025-10-21 05:06:27', '2025-10-21 05:06:27');
INSERT INTO cat_almacenes (id, clave, nombre, sucursal_id, activo, created_at, updated_at) VALUES (55, 'COC-REF', 'Cocina Refrigeranción', 19, true, '2025-10-21 05:07:18', '2025-10-21 05:07:18');
INSERT INTO cat_almacenes (id, clave, nombre, sucursal_id, activo, created_at, updated_at) VALUES (56, 'CAF-PRIN', 'Cafetería-Principal', 19, true, '2025-10-21 05:07:58', '2025-10-21 05:07:58');
INSERT INTO cat_almacenes (id, clave, nombre, sucursal_id, activo, created_at, updated_at) VALUES (57, 'ALM-GEN', 'Almacen General', NULL, true, '2025-10-21 05:08:19', '2025-10-21 05:08:19');
INSERT INTO cat_almacenes (id, clave, nombre, sucursal_id, activo, created_at, updated_at) VALUES (58, 'SELEMTI', 'PRUEBA SELEMTI', 22, true, '2025-10-21 05:08:40', '2025-10-21 05:08:40');


---------------- FORMAS DE PAGO 
'2025-09-17 08:40:57.876762-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (2, 'CREDIT', 'CREDIT', NULL, NULL, NULL, NULL, true, 100, '2025-09-17 08:40:57.876762-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (3, 'DEBIT', 'DEBIT', NULL, NULL, NULL, NULL, true, 100, '2025-09-17 08:40:57.876762-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (4, 'TRANSFER', 'TRANSFER', NULL, NULL, NULL, NULL, true, 100, '2025-09-17 08:40:57.876762-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (5, 'REFUND', 'REFUND', NULL, NULL, NULL, NULL, true, 100, '2025-09-17 08:40:57.876762-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (6, 'PAY_OUT', 'PAY_OUT', NULL, NULL, NULL, NULL, true, 100, '2025-09-17 08:40:57.876762-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (7, 'CASH_DROP', 'CASH_DROP', NULL, NULL, NULL, NULL, true, 100, '2025-09-17 08:40:57.876762-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (8, 'CREDIT_CARD', 'CREDIT_CARD', 'CREDIT', 'VISA', NULL, NULL, true, 100, '2025-09-17 09:06:09.509102-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (9, 'CASH', 'CASH', 'CREDIT', 'CASH', NULL, NULL, true, 100, '2025-09-17 09:10:09.104336-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (343, 'DEBIT_CARD', 'DEBIT_CARD', 'CREDIT', 'MASTER CARD', NULL, NULL, true, 100, '2025-09-17 15:35:19.713525-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (1117, 'CREDIT_CARD', 'CREDIT_CARD', 'CREDIT', 'MASTER CARD', NULL, NULL, true, 100, '2025-09-19 11:43:16.717348-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (1591, 'REFUND', 'REFUND', 'DEBIT', 'CASH', NULL, NULL, true, 100, '2025-09-20 16:43:46.046399-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (1592, 'VOID_TRANS', 'VOID_TRANS', 'DEBIT', 'CASH', NULL, NULL, true, 100, '2025-09-20 16:43:46.046399-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (1675, 'DEBIT_CARD', 'DEBIT_CARD', 'CREDIT', 'VISA', NULL, NULL, true, 100, '2025-09-22 10:04:31.673494-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (11761, 'CUSTOM:tranferencia', 'CUSTOM_PAYMENT', 'CREDIT', 'CUSTOM PAYMENT', 'Tranferencia', 'werwer', true, 100, '2025-10-20 14:43:50.917674-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (11765, 'CUSTOM:tranferencia', 'CUSTOM_PAYMENT', 'CREDIT', 'CUSTOM PAYMENT', 'Tranferencia', '55', true, 100, '2025-10-20 15:49:17.115169-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (11769, 'CUSTOM:tranferencia', 'CUSTOM_PAYMENT', 'CREDIT', 'CUSTOM PAYMENT', 'Tranferencia', 'rrr', true, 100, '2025-10-20 16:06:27.862772-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (11778, 'GIFT_CERT', 'GIFT_CERT', 'CREDIT', 'GIFT_CERTIFICATE', NULL, NULL, true, 100, '2025-10-20 19:09:05.684174-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (11779, 'CUSTOM:tranferencia', 'CUSTOM_PAYMENT', 'CREDIT', 'CUSTOM PAYMENT', 'Tranferencia', '123123', true, 100, '2025-10-20 19:09:17.20293-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (11780, 'CASH_DROP', 'CASH_DROP', 'CREDIT', 'CASH', NULL, NULL, true, 100, '2025-10-20 19:09:35.567954-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (11781, 'PAY_OUT', 'PAY_OUT', 'DEBIT', 'CASH', NULL, NULL, true, 100, '2025-10-20 19:10:13.489315-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (11791, 'CREDIT_CARD', 'CREDIT_CARD', 'CREDIT', 'AMEX', NULL, NULL, true, 100, '2025-10-21 01:34:10.1111-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (11794, 'CUSTOM:tranferencia', 'CUSTOM_PAYMENT', 'CREDIT', 'CUSTOM PAYMENT', 'Tranferencia', '45', true, 100, '2025-10-21 01:35:32.461231-05');
INSERT INTO formas_pago (id, codigo, payment_type, transaction_type, payment_sub_type, custom_name, custom_ref, activo, prioridad, creado_en) VALUES (11802, 'CUSTOM:tranferencia', 'CUSTOM_PAYMENT', 'CREDIT', 'CUSTOM PAYMENT', 'Tranferencia', '66', true, 100, '2025-10-21 01:39:02.762296-05');



--- 




